### ISSUE TITLE
Wrong NEWS date;

### ISSUE THREAD

**Issue by chamiduu** [STEdirisuriya/Covid19-sl-report#1]
![Screenshot from 2020-04-01 11-01-36](https://user-images.githubusercontent.com/41909955/78137391-de08be80-7442-11ea-984d-a276f5cc9667.png)

![Screenshot from 2020-04-01 10-59-33](https://user-images.githubusercontent.com/41909955/78137264-a7cb3f00-7442-11ea-8581-2bb534e82d04.png)

 **It should be ''2020"**

**Comment by supunTE** [comment]
It's Only a tested file. I'll change quickly
